/////////////////////////////////////////////////////////////////////////
// Javascript file generated by ctc2html v4.1
// Copyright (c) 2006-2013 Testwell Oy
// Copyright (c) 2013-2014 Verifysoft Technology GmbH
/////////////////////////////////////////////////////////////////////////
target=location.hash;

function highlight(row, a, b) {
   row.style.cursor = 'pointer';
   if (row.tagName != "TR") {
       row = row.parentNode;
       if (row.tagName != "TR") {
           row = row.parentNode;
       }
   }
   var node = row.parentNode.rows[row.rowIndex-a].firstChild;
   while (node != null) {
      cl = node.getAttribute("class");
      if (cl != null) {
         node.setAttribute("class", cl.replace(/profile/, "highlight"));
      } else {
         cl = node.getAttribute("className");
         node.setAttribute("className", cl.replace(/profile/, "highlight"));
      }
      node = node.nextSibling;
   }
   node = row.parentNode.rows[row.rowIndex-b].firstChild;
   while (node != null) {
      cl = node.getAttribute("class");
      if (cl != null) {
         node.setAttribute("class", cl.replace(/profile/, "highlight"));
      } else {
         cl = node.getAttribute("className");
         node.setAttribute("className", cl.replace(/profile/, "highlight"));
      }
      node = node.nextSibling;
   }
}

function unhighlight(row, a, b) {
   if (row.tagName != "TR") {
       row = row.parentNode;
       if (row.tagName != "TR") {
           row = row.parentNode;
       }
   }
   node = row.parentNode.rows[row.rowIndex-a].firstChild;
   while (node != null) {
      cl = node.getAttribute("class");
      if (cl != null) {
         node.setAttribute("class", cl.replace(/highlight/, "profile"));
      } else {
         cl = node.getAttribute("className");
         node.setAttribute("className", cl.replace(/highlight/, "profile"));
      }
      node = node.nextSibling;
   }
   node = row.parentNode.rows[row.rowIndex-b].firstChild;
   while (node != null) {
      cl = node.getAttribute("class");
      if (cl != null) {
         node.setAttribute("class", cl.replace(/highlight/, "profile"));
      } else {
         cl = node.getAttribute("className");
         node.setAttribute("className", cl.replace(/highlight/, "profile"));
      }
      node = node.nextSibling;
   }
}

function load_profile() {
   if (target == "#a1") {
      parent.index_profile.location = "indexC.html#a1";
      parent.profile.location = "indexD1.html";
   }
   if (target == "#a2") {
      parent.index_profile.location = "indexC.html#a2";
      parent.profile.location = "indexD2.html";
   }
   if (target == "#a3") {
      parent.index_profile.location = "indexC.html#a3";
      parent.profile.location = "indexD3.html";
   }
   if (target == "#a4") {
      parent.index_profile.location = "indexC.html#a4";
      parent.profile.location = "indexD4.html";
   }
}

function load_funcs() {
   if (target == "#ad1") {
      parent.index_funcs.location = "indexH.html#ad1";
      parent.functions.location = "indexB1.html";
   }
   if (target == "#ad2") {
      parent.index_funcs.location = "indexH.html#ad2";
      parent.functions.location = "indexB2.html";
   }
   if (target == "#ad2") {
      parent.index_funcs.location = "indexH.html#ad2";
      parent.functions.location = "indexB2.html";
   }
   if (target == "#ad2") {
      parent.index_funcs.location = "indexH.html#ad2";
      parent.functions.location = "indexB2.html";
   }
}

function load_untested() {
   if (target == "#ufi1") {
      parent.index_untested.location = "indexI.html#ufi1";
      parent.untested.location = "indexU.html";
   }
   if (target == "#ufi2") {
      parent.index_untested.location = "indexI.html#ufi2";
      parent.untested.location = "indexU.html";
   }
   if (target == "#ufi3") {
      parent.index_untested.location = "indexI.html#ufi3";
      parent.untested.location = "indexU.html";
   }
   if (target == "#ufi4") {
      parent.index_untested.location = "indexI.html#ufi4";
      parent.untested.location = "indexU.html";
   }
}
